name: reels_downloader
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.4
  flutter_riverpod: ^0.14.0+3
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.1
  google_mobile_ads: ^0.13.2+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_gallery_saver: ^1.6.9
  lint: ^1.5.3
  open_file: null
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  receive_sharing_intent: ^1.4.5
  share: ^2.0.4
  url_launcher: ^6.0.9
  video_player: ^2.1.12

dev_dependencies:
  build_runner: ^2.1.0
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  flutter_native_splash: ^1.2.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/bitmap2.svg
    - assets/empty.svg
    - assets/logo2.png
    - assets/1.png
    - assets/2.png
    - assets/3.png

flutter_native_splash:
  background_image: assets/logo2.png
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


